default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres_test_app
  password: 123
  host: localhost
  port: 5432

development:
  <<: *default
  database: test_app_development

test:
  <<: *default
  database: test_app_test
